# Generated by Django 4.0.7 on 2022-09-27 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postes',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_categoria', to='blog.postescategoria', verbose_name='Categoria'),
        ),
    ]
