# Generated by Django 4.0.7 on 2022-09-26 00:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Cadastrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado em')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('nome', models.CharField(max_length=60, verbose_name='Nome')),
                ('whatsapp', models.CharField(max_length=20, verbose_name='Whatsapp')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('departamento', models.CharField(max_length=30, verbose_name='Departamento')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('notificacao_whatsapp', models.BooleanField(default=False, verbose_name='Deseja, Receber Informações de novidades dos nossos serviços por whatsapp')),
                ('notificacao_email', models.BooleanField(default=False, verbose_name='Deseja, Receber Informações de novidades dos nossos serviços por email')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Cadastrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado em')),
                ('nome', models.CharField(max_length=30, verbose_name='Departamento')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
