# Generated by Django 4.0.7 on 2022-09-23 20:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Cadastrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado em')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('nome', models.CharField(max_length=30, verbose_name='Categoria')),
            ],
            options={
                'verbose_name_plural': 'Categorias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServicosDestaques',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Cadastrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado em')),
                ('nome', models.CharField(max_length=50, verbose_name='Servico')),
                ('icone', models.ImageField(upload_to='servicos/imagens')),
                ('descricao', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Cadastrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado em')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150, verbose_name='Servico')),
                ('imagem', models.ImageField(default='media/servico_padrao.jpg', upload_to='servicos/imagens')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('slider', models.BooleanField(default=False, verbose_name='Slider')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_servicos', to='servicos.categoria')),
            ],
            options={
                'verbose_name_plural': 'Serviços',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=15, verbose_name='Imagem nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('slider', models.BooleanField(default=False, verbose_name='Ativo')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='galeria/original')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img_servico', to='servicos.servico')),
            ],
            options={
                'verbose_name_plural': 'Imagens',
                'ordering': ['-created_at'],
            },
        ),
    ]
