# Generated by Django 2.2 on 2022-02-06 03:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=30, verbose_name='Categoria')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name_plural': 'Categorias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150, verbose_name='Servico')),
                ('capa', models.ImageField(default='servico_padrao.jpg', upload_to='servicos/imagens')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_servico', to='servicos.Categoria')),
            ],
            options={
                'verbose_name_plural': 'Serviços',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=15, verbose_name='Imagem nome')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='galeria/original')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img_servico', to='servicos.Servico')),
            ],
            options={
                'verbose_name_plural': 'Imagens',
                'ordering': ['-created_at'],
            },
        ),
    ]
