# Generated by Django 3.2 on 2021-09-17 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_auto_20210905_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagem',
            old_name='original',
            new_name='imagem',
        ),
        migrations.AddField(
            model_name='servico',
            name='capa',
            field=models.ImageField(default='servico_padrao.jpg', upload_to='servicos/imagens', verbose_name='Capa'),
        ),
    ]
