# Generated by Django 3.2 on 2022-01-11 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_auto_20210916_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='capa',
            field=models.ImageField(default='servico_padrao.jpg', upload_to='servicos/imagens'),
        ),
    ]
