# Generated by Django 3.2 on 2022-02-06 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento', '0002_apontamento_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apontamento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
