# Generated by Django 3.2 on 2022-01-14 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('gerador_qrcode', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NovoQrCode',
            new_name='QrCode',
        ),
    ]
